export const SET_LOGIN_SUCCESSFUL = 'SET_LOGIN_SUCCESSFUL';
export const SET_CLIENT_ID = 'SET_CLIENT_ID';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';
export const REMOVE_CLIENT_ID = 'REMOVE_CLIENT_ID';

export const SET_CLIENT_BOOKED_WORKOUTS = 'SET_CLIENT_BOOKED_WORKOUTS';
export const FETCH_CLIENT_BOOKED_WORKOUTS_FAILED = 'FETCH_CLIENT_BOOKED_WORKOUTS_FAILED';

export const FETCH_CLASSES_START = 'FETCH_CLASSES_START';
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_FAIL = 'FETCH_CLASSES_FAIL';

export const PURCHASE_CLASSES_START = 'PURCHASE_CLASSES_START';
export const PURCHASE_CLASSES_SUCCESS = 'PURCHASE_CLASSES_SUCCESS';
export const PURCHASE_CLASSES_FAIL = 'PURCHASE_CLASSES_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';
