export const SET_LOGIN_SUCCESSFUL = 'SET_LOGIN_SUCCESSFUL';
export const SET_CLIENT_ID = 'SET_CLIENT_ID';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';
export const REMOVE_CLIENT_ID = 'REMOVE_CLIENT_ID';

export const REMOVE_CLASS = 'REMOVE_CLASS';
export const SET_CLIENT = 'SET_CLIENT';
export const FETCH_CLIENT_FAILED = 'FETCH_CLIENT_FAILED';

export const SET_LOADING = 'SET_LOADING';

