export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_CLIENT_ID = 'SET_CLIENT_ID';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';
export const REMOVE_CLIENT_ID = 'REMOVE_CLIENT_ID';