export const SET_LOGIN_SUCCESSFUL = 'SET_LOGIN_SUCCESSFUL';
export const SET_CLIENT_ID = 'SET_CLIENT_ID';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';
export const REMOVE_CLIENT_ID = 'REMOVE_CLIENT_ID';